#!/usr/bin/env bash
# check-requirements-sync.sh: exits non-zero with a diff when requirements.txt
# differs from a fresh "uv export" output.
# Usage: bash scripts/check-requirements-sync.sh [path/to/uv]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REQUIREMENTS="${REPO_ROOT}/requirements.txt"

# Allow overriding uv binary via argument or PATH
UV="${1:-uv}"
if ! command -v "${UV}" >/dev/null 2>&1; then
  echo "ERROR: uv not found (tried '${UV}'). Install uv: https://docs.astral.sh/uv/" >&2
  exit 2
fi

# Generate fresh export with --no-header (avoids dynamic command-path in the comment)
FRESH="$(mktemp)"
trap 'rm -f "${FRESH}"' EXIT

"${UV}" export \
  --format requirements-txt \
  --no-hashes \
  --no-emit-project \
  --no-dev \
  --no-header \
  -o "${FRESH}" \
  --project "${REPO_ROOT}" 2>/dev/null

# Prepend the GENERATED header we add to the committed file
{
  echo "# GENERATED by uv export - do not hand-edit; see scripts/check-requirements-sync.sh"
  cat "${FRESH}"
} > "${FRESH}.headed"
mv "${FRESH}.headed" "${FRESH}"

if diff -u "${REQUIREMENTS}" "${FRESH}"; then
  echo "OK: requirements.txt is in sync with uv export."
  exit 0
else
  echo ""
  echo "ERROR: requirements.txt is out of sync with uv export." >&2
  echo "Regenerate with:" >&2
  echo "  uv export --format requirements-txt --no-hashes --no-emit-project --no-dev --no-header -o requirements.txt" >&2
  echo "  sed -i '1s/^/# GENERATED by uv export - do not hand-edit; see scripts\/check-requirements-sync.sh\n/' requirements.txt" >&2
  exit 1
fi
